export const specializations = [
  { label: "متخصص قلب و عروق", value: "متخصص قلب و عروق" },
  { label: "دندان پزشک", value: "دندان پزشک" },
  { label: "متخصص پوست", value: "متخصص پوست" },
  { label: "متخصص غدد", value: "متخصص غدد" },
  { label: "متخصص گوارش", value: "متخصص گوارش" },
  { label: "پزشک عمومی", value: "پزشک عمومی"},
  { label: "متخصص زنان و زایمان", value: "متخصص زنان و زایمان" },
  { label: "متخصص خون", value: "متخصص خون" },
  { label: "متخصص مغز و اعصاب", value: "متخصص مغز و اعصاب" },
  { label: "انکولوژیست", value: "انکولوژیست" },
  { label: "چشم پزشک", value: "چشم پزشک"},
  { label: "ارتوپد", value: "ارتوپد" },
  { label: "متخصص گوش و حلق و بینی", value: "متخصص گوش و حلق و بینی"},
  { label: "متخصص اطفال", value: "متخصص اطفال" },
  { label: "روانپزشک", value: "روانپزشک"},
  { label: "متخصص ریه", value: "متخصص ریه" },
  { label: "رادیولوژیست", value: "رادیولوژیست"},
  { label: "روماتولوژیست", value: "روماتولوژیست"},
  { label: "اورولوژیست", value: "اورولوژیست" },
];

export const workDays = [
  { label: "شنبه", value: "saturday" },
  { label: "یکشنبه", value: "sunday" },
  { label: "دوشنبه", value: "monday" },
  { label: "سه شنبه", value: "tuesday" },
  { label: "چهارشنبه", value: "wednesday" },
  { label: "پنج شنبه", value: "thursday" },
  { label: "جمعه", value: "friday" },
];

export const workHours = [
  { label: "09:00", value: "09:00" },
  { label: "09:30", value: "09:30" },
  { label: "10:00", value: "10:00" },
  { label: "10:30", value: "10:30" },
  { label: "11:00", value: "11:00" },
  { label: "11:30", value: "11:30" },
  { label: "12:00", value: "12:00" },
  { label: "12:30", value: "12:30" },
  { label: "13:00", value: "13:00" },
  { label: "13:30", value: "13:30" },
  { label: "14:00", value: "14:00" },
  { label: "14:30", value: "14:30" },
  { label: "15:00", value: "15:00" },
  { label: "15:30", value: "15:30" },
  { label: "16:00", value: "16:00" },
  { label: "16:30", value: "16:30" },
  { label: "17:00", value: "17:00" },
  { label: "17:30", value: "17:30" },
  { label: "18:00", value: "18:00" },
  { label: "18:30", value: "18:30" },
  { label: "19:00", value: "19:00" },
  { label: "19:30", value: "19:30" },
  { label: "20:00", value: "20:00" },
  { label: "20:30", value: "20:30" },
  { label: "21:00", value: "21:00" },
];
